# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sensoris/protobuf/categories/map.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from sensoris.protobuf.types import base_pb2 as sensoris_dot_protobuf_dot_types_dot_base__pb2
from sensoris.protobuf.types import spatial_pb2 as sensoris_dot_protobuf_dot_types_dot_spatial__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='sensoris/protobuf/categories/map.proto',
  package='sensoris.protobuf.categories.map',
  syntax='proto3',
  serialized_options=b'\n\033org.sensoris.categories.mapB\023SensorisMapCategoryP\001\370\001\001',
  serialized_pb=b'\n&sensoris/protobuf/categories/map.proto\x12 sensoris.protobuf.categories.map\x1a\"sensoris/protobuf/types/base.proto\x1a%sensoris/protobuf/types/spatial.proto\"\xa0\x01\n\x0cMapReference\x12=\n\x08\x65nvelope\x18\x01 \x01(\x0b\x32+.sensoris.protobuf.types.base.EventEnvelope\x12Q\n\x12location_reference\x18\x02 \x01(\x0b\x32\x35.sensoris.protobuf.types.spatial.MapLocationReference\"\x96\x01\n\x0bMapCategory\x12@\n\x08\x65nvelope\x18\x01 \x01(\x0b\x32..sensoris.protobuf.types.base.CategoryEnvelope\x12\x45\n\rmap_reference\x18\x02 \x03(\x0b\x32..sensoris.protobuf.categories.map.MapReferenceB7\n\x1borg.sensoris.categories.mapB\x13SensorisMapCategoryP\x01\xf8\x01\x01\x62\x06proto3'
  ,
  dependencies=[sensoris_dot_protobuf_dot_types_dot_base__pb2.DESCRIPTOR,sensoris_dot_protobuf_dot_types_dot_spatial__pb2.DESCRIPTOR,])




_MAPREFERENCE = _descriptor.Descriptor(
  name='MapReference',
  full_name='sensoris.protobuf.categories.map.MapReference',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='envelope', full_name='sensoris.protobuf.categories.map.MapReference.envelope', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='location_reference', full_name='sensoris.protobuf.categories.map.MapReference.location_reference', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=152,
  serialized_end=312,
)


_MAPCATEGORY = _descriptor.Descriptor(
  name='MapCategory',
  full_name='sensoris.protobuf.categories.map.MapCategory',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='envelope', full_name='sensoris.protobuf.categories.map.MapCategory.envelope', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='map_reference', full_name='sensoris.protobuf.categories.map.MapCategory.map_reference', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=315,
  serialized_end=465,
)

_MAPREFERENCE.fields_by_name['envelope'].message_type = sensoris_dot_protobuf_dot_types_dot_base__pb2._EVENTENVELOPE
_MAPREFERENCE.fields_by_name['location_reference'].message_type = sensoris_dot_protobuf_dot_types_dot_spatial__pb2._MAPLOCATIONREFERENCE
_MAPCATEGORY.fields_by_name['envelope'].message_type = sensoris_dot_protobuf_dot_types_dot_base__pb2._CATEGORYENVELOPE
_MAPCATEGORY.fields_by_name['map_reference'].message_type = _MAPREFERENCE
DESCRIPTOR.message_types_by_name['MapReference'] = _MAPREFERENCE
DESCRIPTOR.message_types_by_name['MapCategory'] = _MAPCATEGORY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MapReference = _reflection.GeneratedProtocolMessageType('MapReference', (_message.Message,), {
  'DESCRIPTOR' : _MAPREFERENCE,
  '__module__' : 'sensoris.protobuf.categories.map_pb2'
  # @@protoc_insertion_point(class_scope:sensoris.protobuf.categories.map.MapReference)
  })
_sym_db.RegisterMessage(MapReference)

MapCategory = _reflection.GeneratedProtocolMessageType('MapCategory', (_message.Message,), {
  'DESCRIPTOR' : _MAPCATEGORY,
  '__module__' : 'sensoris.protobuf.categories.map_pb2'
  # @@protoc_insertion_point(class_scope:sensoris.protobuf.categories.map.MapCategory)
  })
_sym_db.RegisterMessage(MapCategory)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
